export const PLANT_ACTION_TYPES = {
    SET_PLANTS: "SET_PLANTS",
    FETCH_PLANTS_START: 'FETCH_PLANTS_START',
    FETCH_PLANTS_SUCCESS: 'FETCH_PLANTS_SUCCESS',
    FETCH_PLANTS_FAILED: 'FETCH_PLANTS_FAILED',
}
