export const months = [
  { label: "Január", value: 1, color: "cyan" },
  { label: "Február", value: 2, color: "cyan" },
  { label: "Március", value: 3, color: "green" },
  { label: "Április", value: 4, color: "green" },
  { label: "Május", value: 5, color: "green" },
  { label: "Június", value: 6, color: "red" },
  { label: "Július", value: 7, color: "red" },
  { label: "Augusztus", value: 8, color: "red" },
  { label: "Szeptember", value: 9, color: "gold" },
  { label: "Október", value: 10, color: "gold" },
  { label: "November", value: 11, color: "gold" },
  { label: "December", value: 12, color: "cyan" },
];
export const monthsColor = {
  1: "cyan",
  2: "cyan",
  3: "green",
  4: "green",
  5: "green",
  6: "red",
  7: "red",
  8: "red",
  9: "gold",
  10: "gold",
  11: "gold",
  12: "cyan",
};
